name = "ONSAS"
uuid = "7d8da659-23aa-453a-9a19-a3d1f6c795f5"
authors = ["to be defined"]
version = "0.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MshReader = "64cd2da2-d71d-431a-81e3-4cf84ef169dd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
MshReader = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
